// lib/nexmo_developer/app/webpacker/javascript/components/search/Search.vue
<template>
  <div class="Wrapper">
    <div class="Wrapper-content">
      <svg class="Vlt-icon Vlt-grey Nxd-search-icon">
        <use xlink:href="/symbol/volta-icons.svg#Vlt-icon-search-full" />
      </svg>


      <div class="Nxd-search-input">
        <div class="Vlt-composite Vlt-composite--appendedicon">
          <div class="Vlt-composite__prepend Vlt-composite__prepend--icon">
            <svg><use xlink:href="/symbol/volta-icons.svg#Vlt-icon-search"/></svg>
          </div>
          <div class="Vlt-input">
            <input
              v-model="query"
              name="query"
              placeholder="Search"
              id="searchbox-test"
              type="text"
              autoComplete="off"
              v-on:keydown.esc="onEscDownHandler"
              v-on:input="onInputHandler"
              ></input>
          </div>
          <div class="Vlt-composite__append Vlt-composite__append--icon Nxd-search-close">
            <svg><use xlink:href="/symbol/volta-icons.svg#Vlt-icon-cross-bold"/></svg>
          </div>
        </div>
      </div>
    </div>

    <div v-show="showResults" class="Nxd-search">
      <div class="Nxd-search__wrapper">
        <div v-show="loading" class="spinner">
          <i class="icon icon-cog"></i>
        </div>
        <div v-show="!loading" class="Nxd-search__wrapper">
          <div class="Nxd-search__results" v-for="result in results" v-bind:key="result.index">
            <h3 class="Nx-search__title">
              {{ resultTitle(result.index) }}
            </h3>
            <div v-if="result.hits.length > 0" >
              <div v-if="isZendeskArticle(result)">
                <ZendeskArticle v-for="hit in result.hits" v-bind:hit="hit" v-bind:key="hitKey(result, hit)"/>
              </div>
              <div v-else-if="isNDPArticle(result)">
                <NDPArticle v-for="hit in result.hits" v-bind:hit="hit" v-bind:key="hitKey(result, hit)"/>
              </div>
            </div>
            <div v-else>
              <p class="Nxd-search--no-results"><i>No results</i></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
import algoliasearch from 'algoliasearch'
import debounce from 'lodash/debounce'
import NDPArticle from './NDPArticle.vue';
import ZendeskArticle from './ZendeskArticle.vue';

export default {
  data: function() {
    return {
      analyticsTriggered: false,
      client: undefined,
      expanded: false,
      loading: false,
      query: '',
      results: [],
      analyticsStrongIndicationOfReadingTimer: undefined,
    }
  },
  created: function() {
    this.client = algoliasearch(
      document.querySelector('meta[name=algolia_application_id]').getAttribute('content'),
      document.querySelector('meta[name=algolia_search_key]').getAttribute('content')
    );
  },
  mounted: function() {
    if (document.querySelector('.Nxd-template')) {
      document.querySelector('.Nxd-template').addEventListener('click', this.onClickOutside.bind(this));
    } else if (document.querySelector('.Adp-landing')) {
      document.querySelector('.Adp-landing .wrapper').addEventListener('click', this.onClickOutside.bind(this));
    }
    this.$el.querySelector('.Nxd-search-icon').addEventListener('click', this.handleSearchToggle.bind(this));
    this.$el.querySelector('.Nxd-search-close').addEventListener('click', this.handleSearchToggle.bind(this));
  },
  onDestroy: function() {
    if (document.querySelector('.Nxd-template')) {
      document.querySelector('.Nxd-template').removeEventListener('click', this.onClickOutside.bind(this));
    } else if (document.querySelector('.Adp-landing')) {
      document.querySelector('.Adp-landing .wrapper').removeEventListener('click', this.onClickOutside.bind(this));
    }
  },
  computed: {
    showResults: function() {
      return this.query != '';
    }
  },
  methods: {
    resultTitle: function(name) {
      if (name == 'zendesk_nexmo_articles') {
        return 'Knowledgebase';
      } else if (name.includes('nexmo_developer')) {
        return 'Nexmo Developer';
      }
    },
    isZendeskArticle: function(result) {
      return result.index == 'zendesk_nexmo_articles';
    },
    isNDPArticle: function(result) {
      return result.index.includes('nexmo_developer');
    },
    hitKey: function(result, hit) {
      return result.index + hit.objectID;
    },
    onClickOutside: function(event) {
      if (this.showResults) {
        this.reset();
      }
      if (this.expanded) {
        this.expanded = false;
      }
    },

    handleSearchToggle: function(event) {
      event.preventDefault();
      event.stopPropagation();

      this.toggleSearch();
    },

    toggleSearch: function(hide) {
      let search = this.$el.querySelector('.Nxd-search-input');
      if (hide === true || search.style.display == 'flex') {
        search.style.display = 'none';
      } else {
        search.style.display = 'flex';
      }
    },
    onEscDownHandler: function(event) {
      if (!this.analyticsTriggered && this.query !== '') {
        this.triggerAnalyticalSearch();
      }
      this.reset();
    },
    reset: function() {
      this.resetAnalyticsListeners();
      this.query = '';
      this.results = [];
      this.loading = false;
    },
    onInputHandler: function(event) {
      event.stopPropagation();
      if (this.query === '') {
        this.reset();
      } else {
        debounce(this.handleSearch.bind(this), 250)(event);
      }
    },
    handleSearch: function(event) {
      this.loading = this.query === '';
      this.analyticsTriggered = false;
      this.performSearch();

      this.resetAnalyticsListeners();
      this.analyticsStrongIndicationOfReadingTimer = setTimeout(this.triggerAnalyticalSearch, 2000);
      window.addEventListener('mousemove', this.triggerAnalyticalSearch);
    },
    performSearch: function(analytics = false) {
      const parameters = Array.from(document.querySelectorAll('meta[name=algolia_index]')).map((element) => {
        return {
          indexName: element.getAttribute('content'),
          query: this.query,
          params: {
            analytics: analytics,
            hitsPerPage: analytics ? 1 : 4
          }
        }
      })

      const searchPromise = this.client.search(parameters)

      if (!analytics) {
        searchPromise.then((response) => {
          this.results = response['results'];
          this.loading = false;
          this.toggleSearch(true);
        })
      }
    },
    resetAnalyticsListeners: function() {
      clearTimeout(this.analyticsStrongIndicationOfReadingTimer);
      window.removeEventListener('mousemove', this.triggerAnalyticalSearch);
    },
    triggerAnalyticalSearch: function() {
      this.performSearch(true);
      this.analyticsTriggered = true;
      this.resetAnalyticsListeners();
    }
  },
  components: {
    ZendeskArticle, NDPArticle
  }
}
</script>
<style scoped>
.Wrapper {
  top: 55px;
  right: 13px;
  display: flex;
  position: absolute;
}
.Wrapper-content {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
}
.Nxd-search-input {
  display: none;
  width: 756px;
  padding: 20px 30px;
  background: white;
  height: 87px;
  border-radius: 8px;
  margin-top: 5px;
  z-index: 10;
}
.Vlt-composite {
  width: 100%;
}
.Nxd-search-icon {
  margin-right: 10px;
}
#searchbox-test {
  border: 1px solid white;
}
</style>

// app/javascript/packs/Search.jsx
import React from 'react'
import debounce from 'lodash/debounce'
import algoliasearch from 'algoliasearch'

class Search extends React.Component {
  constructor(props) {
    super(props)
    this.client = algoliasearch(
      $('meta[name=algolia_application_id]').attr('content'),
      $('meta[name=algolia_search_key]').attr('content')
    )

    this.state = {
      results: [],
      query: '',
      loading: false,
      analyticsTriggered: false
    }

    $(document).on('click', '.wrapper', this.onClickOutside.bind(this))

    this.triggerAnalyticalSearch = this.triggerAnalyticalSearch.bind(this)
  }

  onClickOutside(event) {
    if (this.shouldShowResults()) {
      this.reset()
    }
  }

  handleChange(event) {
    event.persist()
    if (this.state.query === '') {
      this.onChange.bind(this)(event)
    } else {
      debounce(this.onChange.bind(this), 250)(event)
    }
  }

  onChange(event) {
    if (event.target.value === '') {
      return this.reset()
    }

    $('.wrapper').addClass('wrapper--blur')

    this.setState({
      query: event.target.value,
      loading: this.state.query === '',
      analyticsTriggered: false
    }, this.performSearch)

    // Setup event listeners for Analytics
    this.resetAnalyticsListeners()
    this.analyticsStrongIndicationOfReadingTimer = setTimeout(this.triggerAnalyticalSearch, 2000)
    window.addEventListener('mousemove', this.triggerAnalyticalSearch)
  }

  performSearch(analytics = false) {
    const parameters = $('meta[name=algolia_index]').map((index, element) => {
      return {
        indexName: $(element).attr('content'),
        query: this.state.query,
        params: {
          analytics: analytics,
          hitsPerPage: analytics ? 1 : 4
        }
      }
    }).get()

    const searchPromise = this.client.search(parameters)

    if (!analytics) {
      searchPromise.then((response) => {
        this.setState({ results: response['results'], loading: false })
      })
    }
  }

  triggerAnalyticalSearch() {
    this.performSearch(true)
    this.setState({ analyticsTriggered: true })
    this.resetAnalyticsListeners()
  }

  resetAnalyticsListeners() {
    clearTimeout(this.analyticsStrongIndicationOfReadingTimer)
    window.removeEventListener('mousemove', this.triggerAnalyticalSearch)
  }

  handleKeyDown(event) {
    // Handle escape
    if (event.keyCode === 27) {
      if (!this.state.analyticsTriggered && this.state.query != '') {
        this.triggerAnalyticalSearch()
      }

      this.reset()
    }
  }

  reset() {
    $('.wrapper').removeClass('wrapper--blur')
    this.resetAnalyticsListeners()
    this.refs.input.value = '';
    this.setState({
      results: [],
      query: '',
      loading: false,
    })
  }

  shouldShowResults() {
    if (this.state.query != '') {
      return true
    }
  }

  renderHeading(hit) {
    if(!hit.heading) { return }
    if(hit.title == hit.heading) { return }

    return (
      <small> &gt; { hit.heading }</small>
    )
  }

  renderIndexResults(index) {
    return index.hits.map((hit) => {
      if (index.index == 'zendesk_nexmo_articles') {
        return (
          <div className="search-result" key={ index.index + hit.objectID }>
            <a href={ `https://help.nexmo.com/hc/en-us/articles/${hit.id}` } target="_blank">
              <div>
                <span className="meta">{ hit.section.full_path }</span>
                <h3>{ hit.title }</h3>
                <p
                  className="search-highlighted"
                  dangerouslySetInnerHTML={{ __html: `...${hit._snippetResult.body_safe.value}...` }}
                ></p>
              </div>
            </a>
          </div>
        )
      } else if (index.index.includes('nexmo_developer')) {
        return (
          <div className="search-result" key={ index.index + hit.objectID }>
            <a href={ `${hit.path}#${hit.anchor}` }>
              <div>
                <span className="meta">{ hit.product }</span>
                <h3>
                  { hit.title }
                  { this.renderHeading(hit) }
                </h3>

                <p><b>{ hit.description ? hit.description.substring(0, 150) : '' }</b></p>
                <p
                  className="search-highlighted"
                  dangerouslySetInnerHTML={{ __html: `...${hit._snippetResult.body.value}...` }}
                >
                </p>
              </div>
            </a>
          </div>
        )
      }
    })
  }

  renderIndexHeading(indexName) {
    if (indexName == 'zendesk_nexmo_articles') {
      return "Knowlegebase"
    } else if (indexName.includes('nexmo_developer')) {
      return "Nexmo Developer"
    }
  }

  renderIndexResultsEmpty() {
    return (
      <p><i>No results</i></p>
    )
  }

  renderLoading() {
    return (
      <div className="spinner">
        <i className="icon icon-cog"></i>
      </div>
    )
  }

  renderResults() {
    if (this.state.loading) {
      return this.renderLoading()
    } else {
      return this.state.results.map((index) => {
        return(
          <div className="results-index" key={ index.index }>
            <h3>{ this.renderIndexHeading(index.index) }</h3>
            { index.hits.length > 0 ? this.renderIndexResults(index) : this.renderIndexResultsEmpty(index) }
          </div>
        )
      })
    }
  }

  renderClearButton() {
    if (this.state.query !== '') {
      return (
        <i id="search-clear" className="icon icon-times-circle" onClick={ this.reset.bind(this) }></i>
      )
    }
  }

  render() {
    return (
      <div>
        <input
          type="text"
          id="searchbox"
          name="query"
          placeholder="Search"
          name="query"
          autoComplete="off"
          onChange={ this.handleChange.bind(this) }
          onKeyDown={ this.handleKeyDown.bind(this) }
          ref="input"
        />

        { this.renderClearButton() }

        { this.shouldShowResults() &&
          <div className="quicksearch">
            <div className="quicksearch__results">
              { this.renderResults() }
            </div>
          </div>
        }
      </div>
    )
  }
}

export default Search
